# Generated by Django 2.2.7 on 2019-11-08 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('summary', models.CharField(max_length=255, verbose_name='内容')),
                ('a_url', models.CharField(max_length=255, verbose_name='文章地址')),
                ('img_url', models.CharField(max_length=255, verbose_name='图片地址')),
                ('tags', models.CharField(max_length=255, verbose_name='标签')),
            ],
        ),
    ]
